version: '2'
services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: pin_board
      POSTGRES_PASSWORD: yourpassword
    ports:
      - '5432:5432'
    volumes:
      - pin_board-postgres:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch
  web:
    build: .
    links:
      - postgres
    volumes:
      - .:/pin_board
      - ./public/system:/pin_board/public/system
      - ./.bundle:/pin_board/.bundle
    ports:
      - '8000:8000'
    env_file:
      - .pin_board.env
volumes:
  pin_board-storage:
    driver: local
  pin_board-postgres:
    driver: local